version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - costumer_data:/var/lib/mysql
    mem_limit: 512m

volumes:
  costumer_data: